stage: dev
REGION: ${self:custom.region}

#TABLES
PRODUCTS_TABLE: products-table
CATEGORIES_TABLE: categories-table
ORDERS_TABLE: orders-table
CARTS_TABLE: carts-table

#COGNITO
COGNITO_USER_POOL: us-east-1_blJW4tXLf 
COGNITO_CLIENT_ID: 4l0ksvrakmqhe42qgvdcvpsfbb

#BUCKETS
BUCKET_PROFILE_PHOTO: arn:aws:s3:::prof-images